import type { CarModel } from '@/types';

export const mockModels: Partial<CarModel>[] = [
  {
    id: '1',
    brand_id: '1',
    brand_name: 'Tesla',
    brand_slug: 'tesla',
    name: 'Model 3',
    slug: 'tesla-model-3',
    segment: 'Compact',
    body_type: 'Sedan',
    drivetrain: 'Elektrisk',
    drive_type: 'Bakhjulsdrift',
    seats_min: 5,
    seats_max: 5,
    cargo_liters: 425,
    towing_kg: 1000,
    range_wltp_km: 491,
    charge_speed_kw: 170,
    battery_kwh: 60,
    power_hp: 283,
    acceleration_0_100: 6.1,
    model_year_from: 2024,
    model_year_to: null,
    price_from_nok: 449990,
    image_url: 'https://images.pexels.com/photos/4173624/pexels-photo-4173624.jpeg',
    image_primary_url: null,
    intro_text: 'Tesla Model 3 er en kompakt elbil med imponerende rekkevidde og ytelse. Bilen kombinerer sportslighet med praktisk daglig bruk.',
    source_url: null,
    status: 'published',
    confidence_score: 95,
    quality_score: 85,
    review_status: 'reviewed',
    needs_review_reasons: null,
    spec_confidence: null,
    spec_sources: null,
    enrichment_source: null,
    enrichment_confidence: null,
    enrichment_notes: null,
    published: true,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    brand_id: '1',
    brand_name: 'Tesla',
    brand_slug: 'tesla',
    name: 'Model Y',
    slug: 'tesla-model-y',
    segment: 'SUV',
    body_type: 'SUV',
    drivetrain: 'Elektrisk',
    drive_type: 'Firehjulsdrift',
    seats_min: 5,
    seats_max: 7,
    cargo_liters: 854,
    towing_kg: 1600,
    range_wltp_km: 533,
    charge_speed_kw: 250,
    battery_kwh: 75,
    power_hp: 378,
    acceleration_0_100: 5.0,
    model_year_from: 2024,
    model_year_to: null,
    price_from_nok: 549990,
    image_url: 'https://images.pexels.com/photos/15908287/pexels-photo-15908287.jpeg',
    image_primary_url: null,
    intro_text: 'Tesla Model Y er en romslig elektrisk SUV med plass til opptil 7 personer. Perfekt for familier som ønsker elektrisk kjøring uten kompromisser.',
    source_url: null,
    status: 'published',
    confidence_score: 98,
    quality_score: 90,
    review_status: 'reviewed',
    needs_review_reasons: null,
    spec_confidence: null,
    spec_sources: null,
    enrichment_source: null,
    enrichment_confidence: null,
    enrichment_notes: null,
    published: true,
    created_at: '2024-01-16T00:00:00Z',
    updated_at: '2024-01-16T00:00:00Z',
  },
  {
    id: '3',
    brand_id: '2',
    brand_name: 'Mercedes-Benz',
    brand_slug: 'mercedes-benz',
    name: 'EQC',
    slug: 'mercedes-benz-eqc',
    segment: 'SUV',
    body_type: 'SUV',
    drivetrain: 'Elektrisk',
    drive_type: 'Firehjulsdrift',
    seats_min: 5,
    seats_max: 5,
    cargo_liters: 500,
    towing_kg: 1800,
    range_wltp_km: 437,
    charge_speed_kw: 110,
    price_from_nok: 699000,
    image_url: 'https://images.pexels.com/photos/3802508/pexels-photo-3802508.jpeg',
    intro_text: 'Mercedes-Benz EQC kombinerer luksus og elektrisk mobilitet. En premium elektrisk SUV med Mercedes-kvalitet.',
    source_url: null,
    status: 'published',
    confidence_score: 92,
    published: true,
    created_at: '2024-01-17T00:00:00Z',
    updated_at: '2024-01-17T00:00:00Z',
  },
  {
    id: '4',
    brand_id: '3',
    brand_name: 'BMW',
    brand_slug: 'bmw',
    name: 'iX',
    slug: 'bmw-ix',
    body_type: 'SUV',
    drivetrain: 'Elektrisk',
    drive_type: 'Firehjulsdrift',
    seats_min: 5,
    seats_max: 5,
    cargo_liters: 500,
    towing_kg: 2500,
    range_wltp_km: 630,
    charge_speed_kw: 200,
    price_from_nok: 929000,
    image_url: 'https://images.pexels.com/photos/3752169/pexels-photo-3752169.jpeg',
    intro_text: 'BMW iX er en teknologisk avansert elektrisk SUV med imponerende rekkevidde og trekkevne. Perfekt for den krevende familien.',
    source_url: null,
    status: 'published',
    confidence_score: 94,
    published: true,
    created_at: '2024-01-19T00:00:00Z',
    updated_at: '2024-01-19T00:00:00Z',
  },
  {
    id: '5',
    brand_id: '3',
    brand_name: 'BMW',
    brand_slug: 'bmw',
    name: 'i4',
    slug: 'bmw-i4',
    body_type: 'Sedan',
    drivetrain: 'Elektrisk',
    drive_type: 'Bakhjulsdrift',
    seats_min: 5,
    seats_max: 5,
    cargo_liters: 470,
    towing_kg: 1600,
    range_wltp_km: 590,
    charge_speed_kw: 205,
    price_from_nok: 639000,
    image_url: 'https://images.pexels.com/photos/3752169/pexels-photo-3752169.jpeg',
    intro_text: 'BMW i4 er en elegant elektrisk sedan med sportslighet og lang rekkevidde. BMW-kjøreglede i elektrisk form.',
    source_url: null,
    status: 'published',
    confidence_score: 93,
    published: true,
    created_at: '2024-01-20T00:00:00Z',
    updated_at: '2024-01-20T00:00:00Z',
  },
  {
    id: '6',
    brand_id: '4',
    brand_name: 'Audi',
    brand_slug: 'audi',
    name: 'e-tron',
    slug: 'audi-e-tron',
    body_type: 'SUV',
    drivetrain: 'Elektrisk',
    drive_type: 'Firehjulsdrift',
    seats_min: 5,
    seats_max: 5,
    cargo_liters: 660,
    towing_kg: 1800,
    range_wltp_km: 436,
    charge_speed_kw: 150,
    price_from_nok: 779000,
    image_url: 'https://images.pexels.com/photos/3752169/pexels-photo-3752169.jpeg',
    intro_text: 'Audi e-tron er en premium elektrisk SUV med romslig bagasjerom og god trekkevne. Audi-kvalitet møter elektrisk fremtid.',
    source_url: null,
    status: 'published',
    confidence_score: 91,
    published: true,
    created_at: '2024-01-21T00:00:00Z',
    updated_at: '2024-01-21T00:00:00Z',
  },
  {
    id: '7',
    brand_id: '5',
    brand_name: 'Volkswagen',
    brand_slug: 'volkswagen',
    name: 'ID.4',
    slug: 'volkswagen-id4',
    body_type: 'SUV',
    drivetrain: 'Elektrisk',
    drive_type: 'Bakhjulsdrift',
    seats_min: 5,
    seats_max: 5,
    cargo_liters: 543,
    towing_kg: 1200,
    range_wltp_km: 520,
    charge_speed_kw: 135,
    price_from_nok: 469000,
    image_url: 'https://images.pexels.com/photos/3752169/pexels-photo-3752169.jpeg',
    intro_text: 'Volkswagen ID.4 er en populær elektrisk SUV med god plass og praktiske løsninger for familien.',
    source_url: null,
    status: 'published',
    confidence_score: 87,
    published: true,
    created_at: '2024-01-23T00:00:00Z',
    updated_at: '2024-01-23T00:00:00Z',
  },
  {
    id: '8',
    brand_id: '8',
    brand_name: 'Hyundai',
    brand_slug: 'hyundai',
    name: 'Ioniq 5',
    slug: 'hyundai-ioniq-5',
    body_type: 'SUV',
    drivetrain: 'Elektrisk',
    drive_type: 'Firehjulsdrift',
    seats_min: 5,
    seats_max: 5,
    cargo_liters: 527,
    towing_kg: 1600,
    range_wltp_km: 481,
    charge_speed_kw: 220,
    price_from_nok: 469000,
    image_url: 'https://images.pexels.com/photos/3752169/pexels-photo-3752169.jpeg',
    intro_text: 'Hyundai Ioniq 5 er en futuristisk elektrisk SUV med ultra-rask lading og romslig interiør.',
    source_url: null,
    status: 'published',
    confidence_score: 90,
    published: true,
    created_at: '2024-01-25T00:00:00Z',
    updated_at: '2024-01-25T00:00:00Z',
  },
];
